[package]
name = "llmog"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.95"
candle-core = { version = "0.8.2", features = ["accelerate", "metal"] }
candle-nn = { version = "0.8.2", features = ["accelerate", "metal"] }
candle-transformers = { version = "0.8.2", features = ["accelerate", "metal"] }
clap = { version = "4.5.31", features = ["derive"] }
colorous = "1.0.15"
hf-hub = "0.4.1"
itertools = "0.14.0"
regex = "1.11.1"
serde = "1.0.217"
serde_json = "1.0.138"
strip-ansi-escapes = "0.2.1"
termcolor = "1.4.1"
tokenizers = "0.21.0"
ureq = { version = "3.0.5", features = ["json"] }
