[project]
name = "llm_training"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.76.2",
    "python-dotenv>=1.1.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
